// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdorsqmbsyabndlzlvfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb3JzcW1ic3lhYm5kbHpsdmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDU1MDIsImV4cCI6MjA2MTEyMTUwMn0.ymeYxsSdEQwyQR2Nb1mttbUfL9yNUJ3PFHIkCzZrpjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);